---
title: "p8105_hw6_wz2506"
author: "Weiran Zhang"
date: "11/24/2019"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

##load packages
library(tidyverse)
library(readxl)
```


**Problem 1**

Load and clean the data
```{r}
##Load and clean the dataset
birthweight = read_csv("/Users/weiranzhang/Downloads/birthweight.csv") %>% 
janitor::clean_names() %>% 
  mutate(babysex = factor(recode(babysex,"1" = "male","2" = "famle" )),
        frace = factor(recode(frace,"1" = "White","2" = "Black" ,"3" = "Asian", "4"= "Puerto Rican","8"  = "Other", "9" = "Unknown")),
        mrace = factor(recode(mrace,"1" = "White","2" = "Black" ,"3" = "Asian", "4"= "Puerto Rican","8"  = "Other")),
        malform = factor(recode(malform,"0" = "absent","1" = "present")))

anyNA(birthweight) ##check for missing data

birthweight

```

Propose a regression model

By BIC model-building process
```{r}
##Fist check the full model
full_model = lm(bwt ~ ., data = birthweight)
summary(full_model)

full_model %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable()
```

By BIC model selection criterion
```{r}

BIC_model = step(full_model, direction = "backward",
                k = log(nrow(birthweight)), trace = FALSE)
summary(BIC_model)

BIC_model %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable()
```